<a href="https://colab.research.google.com/github/Nonyed/sit774-10.3hd-awesome-canvas-app/blob/main/SIT719_Task_3_1_scikit_learn_commands.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SIT719 – Task 3.1: Collection of scikit-learn commands

This notebook shows a collection of useful **scikit-learn** commands for basic machine learning.
For each command, I include:
- A short explanation of what it does.
- A simple example so that someone new to scikit-learn can follow the workflow.
We will mainly use the classic **iris** dataset for classification examples.

In [31]:
# Import core libraries
import numpy as np
import pandas as pd

# Import scikit-learn components
from sklearn import datasets
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans
from sklearn.model_selection import GridSearchCV

## 1. Loading a built-in dataset – `datasets.load_iris`

**Command:** `datasets.load_iris()`

**What it does:**  
Loads the iris flower dataset that comes bundled with scikit-learn. It returns a
"bunch" object containing feature data, targets (labels) and metadata.

**Why it is useful:**  
It is a convenient way to get a clean dataset for practising machine learning
without needing to download files manually.

In [32]:
# Load the iris dataset
iris = datasets.load_iris()

# Feature matrix (X) and target vector (y)
X = iris.data        # measurements
y = iris.target      # class labels (0, 1, 2)

print("Feature shape:", X.shape)
print("Target shape:", y.shape)
print("Target names:", iris.target_names[:])

Feature shape: (150, 4)
Target shape: (150,)
Target names: ['setosa' 'versicolor' 'virginica']


## 2. Splitting data – `train_test_split`

**Command:** `train_test_split(X, y, test_size=0.2, random_state=42)`

**What it does:**  
Randomly splits the data into a **training set** and a **test set**.

**Why it is useful:**  
We train the model on the training set and evaluate it on the test set.
This helps us estimate how well the model will perform on unseen data.


In [33]:
# Split the iris data into train and test sets (80% / 20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training size:", X_train.shape[0])
print("Test size:", X_test.shape[0])

Training size: 120
Test size: 30


## 3. Feature scaling – `StandardScaler`

**Command:** `StandardScaler().fit_transform(X_train)`

**What it does:**  
Standardises features by removing the mean and scaling to unit variance
(z-score standardisation).

**Why it is useful:**  
Many algorithms (e.g., k-NN, SVM) perform better when all features are on a
similar scale.


In [34]:
scaler = StandardScaler()          # create scaler object
X_train_scaled = scaler.fit_transform(X_train)  # fit on train, transform train
X_test_scaled = scaler.transform(X_test)        # transform test using same scaler

print("First scaled row of X_train:\n", X_train_scaled[0])


First scaled row of X_train:
 [-1.47393679  1.20365799 -1.56253475 -1.31260282]


## 4. Training a classifier – `LogisticRegression`, `.fit()` and `.predict()`

**Commands:**
- `LogisticRegression()` – creates a logistic regression classifier.
- `.fit(X_train, y_train)` – trains the model on labelled data.
- `.predict(X_test)` – predicts labels for new/unseen data.

**Why they are useful:**  
These are core commands for supervised learning – almost every scikit-learn
model uses `.fit()` and `.predict()`.


In [35]:
# Create and train a logistic regression classifier
log_reg = LogisticRegression(max_iter=200)
log_reg.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred_log = log_reg.predict(X_test_scaled)
print("Predicted labels:", y_pred_log[:10])


Predicted labels: [1 0 2 1 1 0 1 2 1 1]


## 5. Evaluating accuracy – `accuracy_score`

**Command:** `accuracy_score(y_test, y_pred)`

**What it does:**  
Calculates the proportion of correct predictions.

**Why it is useful:**  
Accuracy is a simple summary measure of model performance on classification tasks.


In [36]:
acc_log = accuracy_score(y_test, y_pred_log)
print("Logistic Regression accuracy:", acc_log)


Logistic Regression accuracy: 1.0


## 6. Detailed evaluation – `confusion_matrix` and `classification_report`

**Commands:**
- `confusion_matrix(y_test, y_pred)`
- `classification_report(y_test, y_pred)`

**What they do:**  
- `confusion_matrix` shows how many samples were correctly or incorrectly
  classified for each class.
- `classification_report` prints precision, recall and F1-score.

**Why they are useful:**  
They give a more detailed view of performance than accuracy alone, especially
when classes are imbalanced.


In [37]:
cm = confusion_matrix(y_test, y_pred_log)
print("Confusion matrix:\n", cm)

print("\nClassification report:")
print(classification_report(y_test, y_pred_log, target_names=iris.target_names))


Confusion matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



## 7. k-Nearest Neighbours – `KNeighborsClassifier`

**Command:** `KNeighborsClassifier(n_neighbors=5)`

**What it does:**  
Creates a classifier that predicts the label of a sample based on the majority
class among its *k* nearest neighbours in the feature space.

**Why it is useful:**  
It is a simple, intuitive algorithm for classification that often works well
on small datasets.


In [38]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)
y_pred_knn = knn.predict(X_test_scaled)

print("k-NN accuracy:", accuracy_score(y_test, y_pred_knn))


k-NN accuracy: 1.0


## 8. Decision trees – `DecisionTreeClassifier`

**Command:** `DecisionTreeClassifier(max_depth=None, random_state=42)`

**What it does:**  
Builds a tree that splits the data into groups using feature thresholds, trying
to create pure (single-class) leaf nodes.

**Why it is useful:**  
Decision trees are easy to interpret and form the basis of more advanced
ensemble methods like random forests.


In [39]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)   # trees don't strictly need scaled features
y_pred_dt = dt.predict(X_test)

print("Decision Tree accuracy:", accuracy_score(y_test, y_pred_dt))


Decision Tree accuracy: 1.0


## 9. Ensemble method – `RandomForestClassifier`

**Command:** `RandomForestClassifier(n_estimators=100, random_state=42)`

**What it does:**  
Creates an ensemble (collection) of decision trees and averages their
predictions.

**Why it is useful:**  
Random forests are powerful and robust; they often achieve high accuracy with
little parameter tuning.


In [40]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Random Forest accuracy:", accuracy_score(y_test, y_pred_rf))


Random Forest accuracy: 1.0


## 10. Support Vector Machine – `SVC`

**Command:** `SVC(kernel='rbf', C=1.0, gamma='scale')`

**What it does:**  
Creates a Support Vector Machine classifier with a radial basis function (RBF)
kernel.

**Why it is useful:**  
SVMs can model complex, non-linear decision boundaries and often perform very
well on medium-sized datasets.


In [41]:
svc = SVC(kernel='rbf', C=1.0, gamma='scale')
svc.fit(X_train_scaled, y_train)
y_pred_svc = svc.predict(X_test_scaled)

print("SVM accuracy:", accuracy_score(y_test, y_pred_svc))


SVM accuracy: 1.0


## 11. Cross-validation – `cross_val_score`

**Command:** `cross_val_score(model, X, y, cv=5)`

**What it does:**  
Performs k-fold cross-validation: splits the data into `cv` folds, trains on
`cv-1` folds and tests on the remaining fold, repeating this several times.

**Why it is useful:**  
Gives a more reliable estimate of model performance by using multiple train/test
splits instead of just one.


In [42]:
cv_scores = cross_val_score(log_reg, X_train_scaled, y_train, cv=5)
print("Cross-validation scores:", cv_scores)
print("Mean CV accuracy:", cv_scores.mean())


Cross-validation scores: [0.95833333 1.         0.875      1.         0.95833333]
Mean CV accuracy: 0.9583333333333334


## 12. Combining steps – `Pipeline`

**Command:** `Pipeline([('scaler', StandardScaler()), ('model', SVC())])`

**What it does:**  
Chains multiple processing steps together (e.g., scaling then classification) so
they are treated as a single model.

**Why it is useful:**  
Helps avoid data leakage and makes cross-validation and parameter tuning easier.


In [43]:
pipe_svc = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC(kernel='rbf', C=1.0, gamma='scale'))
])

pipe_svc.fit(X_train, y_train)
y_pred_pipe = pipe_svc.predict(X_test)

print("Pipeline (Scaler + SVM) accuracy:", accuracy_score(y_test, y_pred_pipe))


Pipeline (Scaler + SVM) accuracy: 1.0


## 13. Hyper-parameter tuning – `GridSearchCV`

**Command:**
`GridSearchCV(model, param_grid, cv=5)`

**What it does:**  
Tries multiple combinations of hyper-parameters and selects the combination that
performs best under cross-validation.

**Why it is useful:**  
Helps automatically find good model settings instead of choosing parameters by
trial-and-error.


In [44]:
param_grid = {
    'model__C': [0.1, 1, 10],
    'model__gamma': ['scale', 0.1, 0.01]
}

grid = GridSearchCV(
    estimator=pipe_svc,
    param_grid=param_grid,
    cv=3
)

grid.fit(X_train, y_train)

print("Best parameters:", grid.best_params_)
print("Best CV score:", grid.best_score_)


Best parameters: {'model__C': 1, 'model__gamma': 'scale'}
Best CV score: 0.9583333333333334


## 14. Unsupervised learning – `KMeans`

**Command:** `KMeans(n_clusters=3, random_state=42)`

**What it does:**  
Performs k-means clustering, grouping data points into a chosen number of
clusters based only on feature similarity (no labels used).

**Why it is useful:**  
K-means is a simple and popular method for exploratory data analysis when class
labels are unknown.


In [45]:
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X)   # use all data

print("Cluster labels for first 10 samples:", kmeans.labels_[:10])


Cluster labels for first 10 samples: [1 1 1 1 1 1 1 1 1 1]


## 15. Summary

In this notebook I explored a collection of important scikit-learn commands,
including:

- Loading datasets (`datasets.load_iris`)
- Splitting data (`train_test_split`)
- Scaling features (`StandardScaler`)
- Training several classifiers (`LogisticRegression`, `KNeighborsClassifier`,
  `DecisionTreeClassifier`, `RandomForestClassifier`, `SVC`)
- Evaluating models (`accuracy_score`, `confusion_matrix`,
  `classification_report`, `cross_val_score`)
- Building pipelines and tuning hyper-parameters (`Pipeline`, `GridSearchCV`)
- Performing unsupervised learning (`KMeans`)

Together, these commands provide a basic workflow for building, evaluating and
improving machine learning models using scikit-learn.
